import type { Metadata } from "next";
import { headingFont, bodyFont } from "@/lib/font";
import "./globals.css";
import Header from "@/components/layout/Header/page";



export const metadata: Metadata = {
  title: "Interiorfirm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${headingFont.variable} ${bodyFont.variable} antialiased `}
      >
        <Header />
        {children}
        
      </body>
    </html>
  );
}
